### ISSUE TITLE
App crash bug

### ISSUE THREAD

**Issue by gzncland** [bydmm/Startup-Game#34]
按Y确认, 按其他键跳过
## G

产品经理: kokdemo 薪水: 4,000元
按Y确认, 按其他键跳过
## G

程序员: koolob 薪水: 2,000元
按Y确认, 按其他键跳过
## G

程序员: iLeeXu 薪水: 10,000元
按Y确认, 按其他键跳过
## G

程序员: 老猫 薪水: 4,000元
按Y确认, 按其他键跳过
## G

程序员: ltype 薪水: 1,800元
按Y确认, 按其他键跳过
## G

程序员: Ludwig 薪水: 3,000元
按Y确认, 按其他键跳过
## G

/Users/Zapper/Downloads/Startup-Game-master/core/hire_system.rb:82:in `block in hire': undefined method`color_salary' for 49575.2:Float (NoMethodError)
    from /Users/Zapper/Downloads/Startup-Game-master/core/hire_system.rb:79:in `each'
    from /Users/Zapper/Downloads/Startup-Game-master/core/hire_system.rb:79:in`hire'
    from /Users/Zapper/Downloads/Startup-Game-master/core/hire_system.rb:61:in `block in hire?'
    from /Users/Zapper/Downloads/Startup-Game-master/helper/helper.rb:65:in`conform'
    from /Users/Zapper/Downloads/Startup-Game-master/core/hire_system.rb:60:in `hire?'
    from /Users/Zapper/Downloads/Startup-Game-master/core/startup_game.rb:106:in`work_one_week'
    from /Users/Zapper/Downloads/Startup-Game-master/core/startup_game.rb:37:in `mvp'
    from /Users/Zapper/Downloads/Startup-Game-master/core/startup_game.rb:28:in`run'
    from game.rb:22:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from game.rb:36:in`<main>'

**Comment by bydmm** [comment]
Nice report, 看来我必须要多写点测试
